variable "cidr_block" { }
variable "vpc_name" { }
variable "cidr_block_private" { }
variable "azs" { }
variable "ami" { }
variable "instance_type" { }
variable "key_name" { }
variable "private_ip" { }
variable "cidr_block_public" { }
variable "private1_ip" { }
variable "profile" { }